class Row
  attr_accessor title: String

  attr_accessor content: Array[Hash]

  attr_accessor errors: Array

  def initialize: (title: String, content: Array[Hash]) -> void

  def title=: (String title) -> void

  def content=: (Array[Hash] content) -> void

  class TitleMaxSizeError < StandardError
  end

  class ContentMaxSizeError < StandardError
  end
end
